name: SonarQube Analysis - Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-frontend:
    name: SonarQube Scan (Frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      # Frontend setup and tests
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-react/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend-react
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend-react
        run: npm test -- --coverage --watchAll=false --ci

      # SonarCloud scan for frontend
      - name: SonarCloud Scan (Frontend)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
